# Site settings
title: mfakhrusy's personal site
description: mfakhrusy's thought about what he builds and what he think is cool.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "https://mfakhrusy.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: mfakhrusy
user_description: I am a Software Developer. I focus on building things. I love it!
user_title: Software Developer
email: fakhrusy.m@gmail.com
linkedin_username: mfakhrusy
twitter_username: v8areu
github_username:  mfakhrusy
stackoverflow_userid: '5835100'

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
