# Site settings
title: A site where dreams become true
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: mfakhrusy
user_description: I am a website developer. I focus on building things. I love it!
user_title: Freelance Web Developer
email: fakhrusy.m@gmail.com
linkedin_username: mfakhrusy
twitter_username: v8areu
github_username:  mfakhrusy
stackoverflow_userid: '5835100'

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
